### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by mrfambo** [yetzt/tilethief#2]
How to use this ?

**Comment by Dirk--** [comment]
This is how I am using tilethief:
https://bastelbude.grade.de/mediawiki/index.php?title=OpenPlotter#tile_server_.2Fw_cahe.2Bproxy

**Comment by yetzt** [comment]
you should use [tileblaster](https://github.com/yetzt/tileblaster) instead. :) 

it does the same thing, but more neatly and with support for vector tiles.
